### PR TITLE
okta devportal doc changes

### PR DESCRIPTION
**Pull request by pmoghef5**
- added some images for devportal test results .

### CODE REVIEW

**Review by shawnhankim — CHANGES_REQUESTED** [review]
Thanks @pmoghef5 for this PR.
Can you minimize the size of `okta-devportal-signin.png` because it is too big? 😄

**Comment by pmoghef5** [comment]
resolved

**Review by shawnhankim — CHANGES_REQUESTED** [review]
@pmoghef5 : Thank you so much for your diligence and passion here. I just wanted to share the following link to compare and discuss which size is better.

* Option 1. https://github.com/nginx-openid-connect/nginx-oidc-okta/blob/c32f5a0066cc730cbd88f65f2a306ed2e58cdb06/docs/img/login-okta.png

* Option 2 (current PR). https://github.com/nginx-openid-connect/nginx-oidc-okta/blob/c32f5a0066cc730cbd88f65f2a306ed2e58cdb06/docs/img/okta-devportal-signin.png

**Review by shawnhankim — APPROVED** [review]
LGTM! Thanks @pmoghef5 ! 👍

**Pull request merged**
